#!/bin/bash

# 2020-01-15 booboo
# this is a simple implementation for a REST based dummy weather service

#
# create content
#

WEEKDAY=$(LANG=C date +%A)
HOUR=$(LANG=C date +%H)

if [[ $HOUR -lt 6 ]] || [[ $HOUR -gt 20 ]]; then
    CURRENT="It's dark outside!"
    FORECAST="We'll see after sunrise"
else
    case $WEEKDAY in
        'Monday')
            CURRENT="On Mondays the weather around here is always fine"
            FORECAST="Tomorrow it might be even better"
            ;;
        'Tuesday')
            CURRENT="Really sunny"
            FORECAST="Will be colder tomorrow"
            ;;
        'Wednesday')
            CURRENT="Light rain"
            FORECAST="Will be better in the next days"
            ;;
        'Thursday')
            CURRENT="Great weather today"
            FORECAST="Don't really have an idea about tomorrow"
            ;;
        'Friday')
            CURRENT="Quite ok"
            FORECAST="Weather will get worse for the weekend"
            ;;
        'Saturday')
            CURRENT="Not worth going outside"
            FORECAST="Tomorrow, the weather will still be bad"
            ;;
        'Sunday')
            CURRENT="Rain"
            FORECAST="Will get better soon"
            ;;
        *)
            CURRENT="No idea about the current weather"
            FORECAST="We'll see"
            ;;
    esac
fi

#
# return content
#

cat <<EOF
Content-Type: application/json

{
    "meta": {
        "origin": "weatherinfo service of exercise A2"
    },
    "data": {
        "day": "$WEEKDAY",
        "current_weather": "$CURRENT",
        "forecast": "$FORECAST"
    }
}
EOF
